/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AnswerDto } from './answerDto';
import { QuestionDto } from './questionDto';

export interface SurveyDto { 
    surveyId?: number;
    episodeNumber?: number;
    episodeTitle?: string;
    questions?: Array<QuestionDto>;
    answers?: Array<AnswerDto>;
}