/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CheckUsernameResponse { 
    checkUsernameResponseTypeCode?: CheckUsernameResponse.CheckUsernameResponseTypeCodeEnum;
}
export namespace CheckUsernameResponse {
    export type CheckUsernameResponseTypeCodeEnum = 'VALID' | 'INVALID' | 'USERNAME_ALREADY_EXISTS';
    export const CheckUsernameResponseTypeCodeEnum = {
        VALID: 'VALID' as CheckUsernameResponseTypeCodeEnum,
        INVALID: 'INVALID' as CheckUsernameResponseTypeCodeEnum,
        USERNAMEALREADYEXISTS: 'USERNAME_ALREADY_EXISTS' as CheckUsernameResponseTypeCodeEnum
    };
}