/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LeagueUserSummary } from './leagueUserSummary';

export interface GetLeagueDetailsByIdForUserResponse { 
    name?: string;
    leagueUserSummaries?: Array<LeagueUserSummary>;
    admin?: LeagueUserSummary;
    status?: GetLeagueDetailsByIdForUserResponse.StatusEnum;
}
export namespace GetLeagueDetailsByIdForUserResponse {
    export type StatusEnum = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
    export const StatusEnum = {
        NOTSTARTED: 'NOT_STARTED' as StatusEnum,
        INPROGRESS: 'IN_PROGRESS' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum
    };
}