/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LeagueSummaryWithUserDetails { 
    userId?: number;
    leagueId?: number;
    role?: LeagueSummaryWithUserDetails.RoleEnum;
    totalPoints?: number;
    totalNumberOfPlayers?: number;
    placement?: number;
    name?: string;
    status?: LeagueSummaryWithUserDetails.StatusEnum;
}
export namespace LeagueSummaryWithUserDetails {
    export type RoleEnum = 'USER' | 'ADMIN';
    export const RoleEnum = {
        USER: 'USER' as RoleEnum,
        ADMIN: 'ADMIN' as RoleEnum
    };
    export type StatusEnum = 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETED';
    export const StatusEnum = {
        NOTSTARTED: 'NOT_STARTED' as StatusEnum,
        INPROGRESS: 'IN_PROGRESS' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum
    };
}