/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface QuestionDto { 
    questionId?: number;
    questionNumber?: number;
    question?: string;
    questionTypeCode?: QuestionDto.QuestionTypeCodeEnum;
    correctAnswer?: string;
    possiblePoints?: number;
}
export namespace QuestionDto {
    export type QuestionTypeCodeEnum = 'SINGLE_CONTESTANT_PICK' | 'MULTIPLE_CONTESTANT_PICK' | 'TRIBE_PICK';
    export const QuestionTypeCodeEnum = {
        SINGLECONTESTANTPICK: 'SINGLE_CONTESTANT_PICK' as QuestionTypeCodeEnum,
        MULTIPLECONTESTANTPICK: 'MULTIPLE_CONTESTANT_PICK' as QuestionTypeCodeEnum,
        TRIBEPICK: 'TRIBE_PICK' as QuestionTypeCodeEnum
    };
}