/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateLeagueResponse } from '../model/createLeagueResponse';
import { GetLeagueDetailsByIdForUserResponse } from '../model/getLeagueDetailsByIdForUserResponse';
import { GetLeagueSummariesForUser } from '../model/getLeagueSummariesForUser';
import { LeagueBody } from '../model/leagueBody';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LeagueControllerService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createLeague(body: LeagueBody, observe?: 'body', reportProgress?: boolean): Observable<CreateLeagueResponse>;
    public createLeague(body: LeagueBody, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CreateLeagueResponse>>;
    public createLeague(body: LeagueBody, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CreateLeagueResponse>>;
    public createLeague(body: LeagueBody, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling createLeague.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CreateLeagueResponse>('post',`${this.basePath}/league`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param leagueId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteLeague(leagueId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteLeague(leagueId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteLeague(leagueId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteLeague(leagueId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (leagueId === null || leagueId === undefined) {
            throw new Error('Required parameter leagueId was null or undefined when calling deleteLeague.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/league/${encodeURIComponent(String(leagueId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param leagueId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLeagueDetailsById(leagueId: string, observe?: 'body', reportProgress?: boolean): Observable<GetLeagueDetailsByIdForUserResponse>;
    public getLeagueDetailsById(leagueId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetLeagueDetailsByIdForUserResponse>>;
    public getLeagueDetailsById(leagueId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetLeagueDetailsByIdForUserResponse>>;
    public getLeagueDetailsById(leagueId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (leagueId === null || leagueId === undefined) {
            throw new Error('Required parameter leagueId was null or undefined when calling getLeagueDetailsById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GetLeagueDetailsByIdForUserResponse>('get',`${this.basePath}/league/${encodeURIComponent(String(leagueId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLeaguesForUser(observe?: 'body', reportProgress?: boolean): Observable<GetLeagueSummariesForUser>;
    public getLeaguesForUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetLeagueSummariesForUser>>;
    public getLeaguesForUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetLeagueSummariesForUser>>;
    public getLeaguesForUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GetLeagueSummariesForUser>('get',`${this.basePath}/league`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
