spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fantasy-turned-real
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api

api:
  jwt:
    secret: ajsdfiouw9803u2jfid023n0ru3190nc1303